x-app-common: &app_common
  image: 79d750d03a8d64371c6ad9abbf81c70dd0557e7bfbbefcf5f25a64e0c686582b
  environment:
    QUARKUS_REDIS_HOSTS: redis://redis:6379
    REDIS_HOST: redis
    REDIS_PORT: 6379
    QUARKUS_HTTP_PORT: "8080"
    REDIS_MAX_POOL_SIZE: 100
    REDIS_MAX_POOL_WAITING: 0
    REST_CLIENT_CONNECT_POOL_SIZE: 128
    WRITER_BATCH_SIZE: 512
    WRITER_CONSUMER_COUNT: 1
  depends_on:
    redis:
      condition: service_started
  restart: unless-stopped

services:
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--save", "", "--appendonly", "no", "--maxmemory", "80mb", "--maxmemory-policy", "allkeys-lfu", "--tcp-backlog", "511"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 2s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 85M
    restart: unless-stopped
    networks:
      - backend

  app1:
    <<: *app_common
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: 120M
    networks:
      - backend
      - payment-processor

  app2:
    <<: *app_common
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: 120M
    networks:
      - backend
      - payment-processor

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - app1
      - app2
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ulimits:
      nofile: 200000
    command: [ "sh","-c","nginx -t && exec nginx -g 'daemon off;'" ]
    restart: on-failure:3
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 25M
    networks:
      - backend

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true