x-app-common: &app_common
  image: 01c36507d28a75b52c07b296d8a3b3c64ba66faf1f163338ffd1500be05766f2
  environment:
    QUARKUS_REDIS_HOSTS: redis://redis:6379
    REDIS_HOST: redis
    REDIS_PORT: 6379
    QUARKUS_HTTP_PORT: "8080"
    REDIS_MAX_POOL_SIZE: 250
    REDIS_MAX_POOL_WAITING: 250
    REST_CLIENT_CONNECT_POOL_SIZE: 256
    WRITER_BATCH_SIZE: 128
    WRITER_CONSUMER_COUNT: 6
  depends_on:
    redis:
      condition: service_started
  restart: unless-stopped

services:
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--save", "", "--appendonly", "no", "--maxmemory", "64mb", "--maxmemory-policy", "allkeys-lru"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 2s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 40M
    restart: unless-stopped
    networks:
      - backend

  app1:
    <<: *app_common
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: 130M
    networks:
      - backend
      - payment-processor

  app2:
    <<: *app_common
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: 130M
    networks:
      - backend
      - payment-processor

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - app1
      - app2
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ulimits:
      nofile: 200000
    command: [ "sh","-c","nginx -t && exec nginx -g 'daemon off;'" ]
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 65M
    networks:
      - backend

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true